Refactor: use jsonc-parser, since the build in parser is deprecated
vaibhavsingh97/nightwatchjs-schematics pull request #17
Opened 2022-08-11 08:53 UTC by swrdfish

2022-08-18 14:06 UTC, vaibhavsingh97 requested changes

2022-08-18 14:06 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/index.ts
> +            version: '',
we don't need `version` here

2022-08-18 14:06 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/util.ts
> +  // const packageJsonAst = readPackageJson(tree);
Please remove this comment

2022-08-18 14:06 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/index.ts
> +      throw new SchematicsException('Angular version not found');
```suggestion
      throw new SchematicsException('Angular project not found');
```

2022-08-18 14:06 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/dependencies.ts
> +  try {
Any specific reason to add `try` block?

2022-08-18 14:06 UTC, vaibhavsingh97 commented on package.json
> +    "nightwatch": "^2.1.8"
can you also increase nightwatch version to the latest one

2022-08-23 08:12 UTC, vaibhavsingh97 requested changes

2022-08-23 08:12 UTC, vaibhavsingh97 commented on tsconfig.json
> +    "rootDir": "/",
We should use `rootDirs` if one or more folders act as a source folder for the compilation.
```json
"rootDirs": ["src/", "test/"]
```
Ref: https://www.typescriptlang.org/tsconfig#rootDirs

2022-08-23 08:12 UTC, vaibhavsingh97 commented on tsconfig.spec.json
> -  "extends": "./tsconfig.json",
Since we have removed this file, can you please migrate the `index_spec.ts` file to the `test` directory?

2022-08-23 08:12 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/index.ts
> +    }
I think this condition will make sure schematics will run on Angular Project only. As of now, users can run schematics on Typescript projects as well. So if we add this condition, we should also remove typescript support.

2022-08-23 08:12 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/dependencies.ts
> +    if (depsNode  && depsNode.type === 'object') {
```suggestion
    if (depsNode?.type === 'object') {
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/dependencies.ts
> +  try {
I don't think it's necessary here

2022-08-23 08:12 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/json-utils.ts
> +  if (node.parent?.children && node.parent.children.length > 0) {
```suggestion
  if (node?.parent?.children.length > 0) {
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testDependency_spec.ts
> +                "name": "blah",
```suggestion
                "name": "test",
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testDependency_spec.ts
> +                "name": "blah",
```suggestion
                "name": "test",
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testDependency_spec.ts
> +                "name": "blah",
```suggestion
                "name": "test",
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testDependency_spec.ts
> +                "name": "blah",
```suggestion
                "name": "test",
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testDependency_spec.ts
> +                "name": "blah",
```suggestion
                "name": "test",
```

2022-08-23 08:12 UTC, vaibhavsingh97 commented on test/testUtility_spec.ts
> +    "name": "blah",
```suggestion
    "name": "test",
```

2022-08-23 08:16 UTC, swrdfish commented on src/schematics/nightwatch/index.ts
> +    }
with current implementation, it does not work with typescript project as angular.json is not present. If that is required we can do another release with typescript project support.

2022-08-23 08:44 UTC, swrdfish commented on src/schematics/nightwatch/utility/dependencies.ts
> +  try {
removed

2022-08-23 08:46 UTC, swrdfish commented on tsconfig.json
> +    "rootDir": "/",
fixed

2022-08-23 08:46 UTC, swrdfish commented on src/schematics/nightwatch/index.ts
> +    }
updated `Readme` for now

2022-08-23 09:00 UTC, vaibhavsingh97 commented on test/execution_spec.ts
> +// import { Tree } from '@angular-devkit/schematics';
Please remove comment

2022-08-23 09:01 UTC, vaibhavsingh97 commented on src/schematics/nightwatch/utility/dependencies.ts
> +      // const { end, start } = depNode;
From here as well

2022-08-23 09:06 UTC, vaibhavsingh97 approved these changes

2022-08-23 09:09 UTC, merged